Yoceyder.WebUI/Controllers/ChildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yoceyder.WebUI.Entity;
using Yoceyder.WebUI.Models.ViewModels;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class ChildController : Controller
    {
        private IUnitOfWork uow;

        public ChildController(IUnitOfWork _uow)
        {
            uow = _uow;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.idal = (id);
            return View();
        }
        [HttpPost]
        public IActionResult Create(int id, Child entity)
        {
            if (ModelState.IsValid)
            {
                uow.Children.SaveChild(entity);
                TempData["message"] = $"{entity.Cocuk_AdiSoyadi} yardım başarılı bir şekilde eklendi.";
                return Redirect("~/Parents/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(uow.Children.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id ,Child entity)
        {
            if (ModelState.IsValid)
            {
                uow.Children.UpdateChild(entity);
                TempData["message"] = $"{entity.Cocuk_AdiSoyadi} kayıt başarılı bir şekilde güncellendi.";
                return Redirect("~/Child/Profile/" + id);
            }
            return View(entity);
        }

        [HttpGet]
        public IActionResult Profile(int id)
        {
            Child childs = new Child();
            childs = uow.Children.GetById(id);
            var sch = uow.Scholarships.GetAll().Where(k => k.Burs_Cocuk_Id == id);
            CSViewModel cs = new CSViewModel();
            cs.Child = childs;
            cs.Scholarship = sch;
            return View(cs);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(uow.Children.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id,int id2)
        {
            uow.Children.DeleteChild(id);
            TempData["message"] = $"{id} numaralı kayıt silindi.";

            return Redirect("~/Parents/Profile/" + id2);
        }
    }
}

Yoceyder.WebUI/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yoceyder.WebUI.Entity;
using Yoceyder.WebUI.Models;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class DonationController : Controller
    {
        private IUnitOfWork uow;

        public DonationController(IUnitOfWork _uow)
        {
            uow = _uow;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.idal = (id);
            return View();
        }
        [HttpPost]
        public IActionResult Create(int  id ,Donation entity)
        {
            if (ModelState.IsValid)
            {
                uow.Donations.SaveDonation(entity);
                TempData["message"] = $"{entity.Yardim_Tur} yardım başarılı bir şekilde eklendi.";
                return Redirect("~/Parents/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(uow.Donations.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id, Donation entity)
        {
            if (ModelState.IsValid)
            {
                uow.Donations.UpdateDonation(entity);
                TempData["message"] = $"{entity.Yardim_Tur} yardım başarılı bir şekilde güncellendi.";
                return Redirect("~/Parents/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
              
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {

            return View(uow.Donations.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id, int id2)
        {
            uow.Donations.DeleteDonation(id);
            TempData["message"] = $"{id} numaralı kayıt silindi.";
            return Redirect("~/Parents/Profile/" + id2);
        }
    }
}

Yoceyder.WebUI/Controllers/ParentsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Yoceyder.WebUI.Entity;
using Yoceyder.WebUI.Models.ViewModels;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class ParentsController : Controller
    {
        private IUnitOfWork uow;

        public ParentsController(IUnitOfWork _uow )
        {
            uow = _uow;
        }


        public IActionResult Index()
        {
            return View(uow.Parents.GetAll());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(uow.Parents.GetAll(), "Vasi_Id", "Vasi_Adisoyadi");
            return View(uow.Parents.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id,Parent entity)
        {
            if (ModelState.IsValid)
            {
                uow.Parents.UpdateParent(entity);
                TempData["message"] = $"{entity.Vasi_AdiSoyadi} kayıt başarılı bir şekilde güncellendi.";
                return Redirect("~/Parents/Profile/" + id);
            }
            return View(entity);
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View(new Parent());
        }
        [HttpPost]
        public IActionResult Create(Parent entity)
        {
            
            if (ModelState.IsValid)
            {
                uow.Parents.SaveParent(entity);
                TempData["message"] = $"{entity.Vasi_AdiSoyadi} kayıt başarılı bir şekilde eklendi.";
                return RedirectToAction("Index");
            }
           
            return View(entity);
            
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(uow.Parents.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id)
        {
            uow.Parents.DeleteParent(id);
            TempData["message"] = $"{id} numaralı kayıt silindi.";

            return RedirectToAction("Index");

        }
        
        [HttpGet]
        public IActionResult Profile(int id)
        {
            Parent prnt = new Parent();
            prnt = uow.Parents.GetById(id); 
            var dnt = uow.Donations.GetAll().Where(k=>k.Yardim_Vasi_Id == id);
            var chl = uow.Children.GetAll().Where(k => k.Vasi_Id == id);
            PCDViewModel pcd = new PCDViewModel();
            pcd.Parent = prnt;
            pcd.Donation = dnt;
            pcd.Child = chl;

            return View(pcd);
        }

        public IActionResult Dene()
        {
            return View();
        }
    }
}

Yoceyder.WebUI/Views/Parents/Create.cshtml
@model Parent
@{
    ViewData["Title"] = "Create";
}

    <div class="container">
        <h1>VASİ OLUŞTUR</h1>
        <br />

        <form asp-controller="parents" asp-action="create" method="post" enctype="multipart/form-data" >
            <div class="form-group">
                <div class="form-group">
                    <select class="form-control" asp-for="Vasi_Dosya">
                        <option>DOSYA1</option>
                        <option>DOSYA2</option>
                        <option>DOSYA3</option>
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="Vasi_Tc">VASİ TC NO </label>
                    <input type="text" asp-for="Vasi_Tc" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_AdiSoyadi">VASİ ADSOYAD</label>
                    <input type="text" asp-for="Vasi_AdiSoyadi" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Telefon"> TELEFON </label>
                    <input type="text" asp-for="Vasi_Telefon" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Il"> İL </label>
                    <input type="text" asp-for="Vasi_Il" class="form-control">
                </div>

                <div class="form-group">
                    <label asp-for="Vasi_Ilce"> İLÇE </label>
                    <input type="text" asp-for="Vasi_Ilce" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Adres"> ADRES </label>
                    <textarea asp-for="Vasi_Adres" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Iban"> İBAN </label>
                    <input type="text" asp-for="Vasi_Iban" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Evdurumu"> EV DURUMU </label>
                    <input type="text" asp-for="Vasi_Evdurumu" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Kiramiktari"> KİRA MİKTARI </label>
                    <input type="text" asp-for="Vasi_Kiramiktari" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Maas"> MAAŞ DURUMU </label>
                    <input type="text" asp-for="Vasi_Maas" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Maasmiktari"> MAAŞ MİKTARI </label>
                    <input type="text" asp-for="Vasi_Maasmiktari" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Vasi_Cocuksayisi"> BAKILAN ÇOCUK SAYISI </label>
                    <input type="text" asp-for="Vasi_Cocuksayisi" class="form-control">
                </div>

                <div class="form-group">
                    <label asp-for="Vasi_Kayittarihi"> KAYIT TARİHİ </label>
                    <input  asp-for="Vasi_Kayittarihi" class="form-control">
                </div>

                <div class="form-group">
                    <label asp-for="Vasi_Guncellemetarihi"> GÜNCELLEME TARİHİ </label>
                    <input  asp-for="Vasi_Guncellemetarihi" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">OLUŞTUR</button>
                <button class="btn btn-danger" asp-controller="parents" asp-action="index">İPTAL</button>
          </div>
    </form>
</div>

Yoceyder.WebUI/Views/Parents/Delete.cshtml
@model Parent
@{
    ViewData["Title"] = "Delete";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2>
                <b> @Model.Vasi_AdiSoyadi</b> isimli kayıdı silmek istiyormusunuz ?
            </h2>

            <form asp-controller="Parents" asp-action="Delete" method="post">
                <input type="hidden" asp-for="Vasi_Id" />
                <button type="submit" class="btn btn-primary">SİL</button>
                <a class="btn btn-danger" asp-controller="Parents" asp-action="profile" asp-route-id="@Model.Vasi_Id">
                    İPTAL
                </a>
            </form>
        </div>
    </div>
</div>

Yoceyder.WebUI/Views/Parents/Edit.cshtml
@model Parent
@{
    ViewData["Title"] = "Add";
}


    <div class="container">
        <h1>VASİ BİLGİLERİ DÜZENLE </h1>
        <br />

        <form asp-controller="parents" asp-action="edit"  asp-route-id="@Model.Vasi_Id" method="post" enctype="multipart/form-data">
            <input type="hidden" asp-for="Vasi_Id" />
            <input type="hidden" asp-for="Vasi_Resim" />
            <div class="form-group">
                <select class="form-control" asp-for="Vasi_Dosya">
                    <option>DOSYA1</option>
                    <option>DOSYA2</option>
                    <option>DOSYA3</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Tc">VASİ TC NO </label>
                <input type="text" asp-for="Vasi_Tc" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_AdiSoyadi">VASİ ADSOYAD</label>
                <input type="text" asp-for="Vasi_AdiSoyadi" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Telefon"> TELEFON </label>
                <input type="text" asp-for="Vasi_Telefon" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Il"> İL </label>
                <input type="text" asp-for="Vasi_Il" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Vasi_Ilce"> İLÇE </label>
                <input type="text" asp-for="Vasi_Ilce" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Adres"> ADRES </label>
                <textarea asp-for="Vasi_Adres" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Iban"> İBAN </label>
                <input type="text" asp-for="Vasi_Iban" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Evdurumu"> EV DURUMU </label>
                <input type="text" asp-for="Vasi_Evdurumu" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Kiramiktari"> KİRA MİKTARI </label>
                <input type="text" asp-for="Vasi_Kiramiktari" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Maas"> MAAŞ DURUMU </label>
                <input type="text" asp-for="Vasi_Maas" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Maasmiktari"> MAAŞ MİKTARI </label>
                <input type="text" asp-for="Vasi_Maasmiktari" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Vasi_Cocuksayisi"> BAKILAN ÇOCUK SAYISI </label>
                <input type="text" asp-for="Vasi_Cocuksayisi" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Vasi_Kayittarihi"> KAYIT TARİHİ </label>
                <input type="text" asp-for="Vasi_Kayittarihi" class="form-control" />
            </div>

            <div class="form-group">
                <label asp-for="Vasi_Guncellemetarihi"> GÜNCELLEME TARİHİ </label>
                <input type="text" asp-for="Vasi_Guncellemetarihi" class="form-control" />
            </div>
            <button type="submit" class="btn btn-primary">KAYDET</button>
            <a class="btn btn-danger " asp-controller="Parents" asp-action="profile" asp-route-id="@Model.Vasi_Id">
                İPTAL
            </a>
        </form>
    </div>

Yoceyder.WebUI/Views/Parents/Index.cshtml
@model IEnumerable<Parent>
@{
    ViewData["Title"] = "AllParents";
}
<div class="container-fluid  bg-light p-3">
    <div class="row">
        <div class="col-md-6">
            <a class="btn btn-danger btn-sm" asp-controller="parents" asp-action="create">
                Kayıt Ekle
            </a>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 ">
            <div class="table-responsive p-3 ">

                <table id="datatables" class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th> VASİYE GİT </th>
                            <th> DOSYA TUR </th>
                            <th> TC </th>
                            <th> ADI SOYADI </th>
                            <th> TELEFON </th>
                            <th> İL </th>
                            <th> İLÇE </th>
                            <th> ADRES </th>
                            <th> IBAN </th>
                            <th> EV DURUMU </th>
                            <th> KİRA MİKTARI </th>
                            <th> MAAŞ </th>
                            <th> MAAŞ MİKTARI </th>
                            <th> BAKILAN ÇOCUK SAYISI </th>
                            <th> KAYIT TARİHİ </th>
                            <th> GÜNCELLEME TARİHİ </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Vasi_Dosya == "Dosya1")
                            {

                            }
                            <tr>
                                <th><a class="btn btn-success" asp-controller="Parents" asp-action="Profile" asp-route-id="@item.Vasi_Id"> GİT </a></th>
                                <th>@item.Vasi_Dosya</th>
                                <th>@item.Vasi_Tc</th>
                                <th>@item.Vasi_AdiSoyadi</th>
                                <th>@item.Vasi_Telefon</th>
                                <th>@item.Vasi_Il</th>
                                <th>@item.Vasi_Ilce</th>
                                <th>@item.Vasi_Adres</th>
                                <th>@item.Vasi_Iban</th>
                                <th>@item.Vasi_Evdurumu</th>
                                <th>@item.Vasi_Kiramiktari</th>
                                <th>@item.Vasi_Maas</th>
                                <th>@item.Vasi_Maasmiktari</th>
                                <th>@item.Vasi_Cocuksayisi</th>
                                <th>@item.Vasi_Kayittarihi.ToShortDateString()</th>
                                <th>@item.Vasi_Guncellemetarihi.ToShortDateString()</th>


                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <th> VASİYE GİT </th>
                            <th> DOSYA TUR </th>
                            <th> TC </th>
                            <th> ADI SOYADI </th>
                            <th> TELEFON </th>
                            <th> İL </th>
                            <th> İLÇE </th>
                            <th> ADRES </th>
                            <th> IBAN </th>
                            <th> EV DURUMU </th>
                            <th> KİRA MİKTARI </th>
                            <th> MAAŞ </th>
                            <th> MAAŞ MİKTARI </th>
                            <th> BAKILAN ÇOCUK SAYISI </th>
                            <th> KAYIT TARİHİ </th>
                            <th> GÜNCELLEME TARİHİ </th>

                        </tr>
                    </tfoot>
                </table>

            </div>

        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript" class="init">

        $(document).ready(function () {
            $('#datatables').DataTable();
        });

    </script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
}

Yoceyder.WebUI/Views/Parents/Profile.cshtml
@model PCDViewModel
@{
    ViewData["Title"] = "Profile";
}
    <div class="m-3">
        <div class="card text-center ">
            <div class="card-header">
                <h4> PROFİL BİLGİLERİ </h4>
            </div>
            <div class="card-body">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-10">
                            <div class="card">
                                <div class="card-body">
                                    <table class="table table-responsive ">
                                        <thead>
                                            <tr>
                                                <th scope="col"> TC KİMLİK </th>
                                                <th scope="col">İSİM SOYİSİM</th>
                                                <th scope="col">TELEFON</th>
                                                <th scope="col">BAKILAN ÇOCUK SAYISI </th>
                                                <th scope="col">IBAN  </th>
                                                <th scope="col">KAYIT TARİHİ </th>
                             
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@Model.Parent.Vasi_Tc</td>
                                                <td> @Model.Parent.Vasi_AdiSoyadi</td>
                                                <td>@Model.Parent.Vasi_Telefon </td>
                                                <td>@Model.Parent.Vasi_Cocuksayisi</td>
                                                <td>@Model.Parent.Vasi_Iban</td>
                                                <td>@Model.Parent.Vasi_Kayittarihi</td>
                                                
                                            </tr>
                                        </tbody>
                                        <thead>
                                            <tr>
                                                <th scope="col"> İL / İLÇE </th>
                                                <th scope="col">ADRES</th>
                                                <th scope="col">MAAŞ</th>
                                                <th scope="col">MAAŞ MİKTARI  </th>
                                                <th scope="col">EV DURUMU</th>
                                                <th scope="col">KİRA MİKTARI  </th>

                                            </tr>
                                        </thead>
                                        
                                        <tbody>
                                            <tr>
                                                <td>@Model.Parent.Vasi_Il / @Model.Parent.Vasi_Ilce</td>
                                                <td>  @Model.Parent.Vasi_Adres</td>
                                                <td>@Model.Parent.Vasi_Maas</td>
                                                <td>   @Model.Parent.Vasi_Maasmiktari</td>
                                                <td> @Model.Parent.Vasi_Evdurumu </td>
                                                <td>@Model.Parent.Vasi_Kiramiktari </td>

                                            </tr>
                                        </tbody>
                                        <thead>
                                            <tr>
                                                <th scope="col">GÜNCELLEME TARİHİ </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@Model.Parent.Vasi_Guncellemetarihi</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                       
                        <div class="col-md-2 ">
                            <div class="card table-responsive" style="width: 100%;">
                                <img src="~/images/images.png" class="card-img-top" alt="...">
                                <br />
                                <a class="btn btn-primary btn-sm" asp-controller="parents" asp-action="edit" asp-route-id="@Model.Parent.Vasi_Id">
                                    DÜZENLE
                                </a>
                                <a class="btn btn-danger btn-sm" asp-controller="parents" asp-action="delete" asp-route-id="@Model.Parent.Vasi_Id">
                                    PROFİLİ SİL
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card text-center">
                <div class="card-header">
                    <h3>  ÇOCUKLAR </h3>

                    <a class="btn btn-danger btn-sm" asp-controller="Child" asp-action="Create" asp-route-id="@Model.Parent.Vasi_Id">
                        ÇOCUK EKLE
                    </a>
                </div>
                <div class="container">
                    <div class="row">

                        @foreach (var item in Model.Child)
                        {
                            <div class="col-md-3">
                                <br />
                                <a asp-controller="Child" asp-action="Profile" asp-route-id="@item.Cocuk_Id">
                                    <div class="card" style="width: 10rem;">
                                        <img class="card-img-top" src="~/images/imagess.png" alt="Card image cap">
                                        <div class="card-body">
                                            <p class="card-text">
                                                <h6>
                                                    @item.Cocuk_AdiSoyadi
                                                </h6>
                                            </p>
                                        </div>
                                    </div>
                                </a>
                                <br />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="card text-center">
            <div class="card-header">
                <h3>  YARDIMLAR </h3>

                <a class="btn btn-danger btn-sm" asp-controller="Donation" asp-action="Create" asp-route-id="@Model.Parent.Vasi_Id">
                    YARDIM EKLE
                </a>
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12 p-3">
                        <div class="table-responsive">
                            <table id="datatables" class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th scope="col">TÜR</th>
                                        <th scope="col"> ÜRÜN </th>
                                        <th scope="col"> MİKTAR</th>
                                        <th scope="col">AÇIKLAMA</th>
                                        <th scope="col">TARİH</th>
                                        <th scope="col">Y: ADI SOYADI</th>
                                        <th scope="col">Y: TELEFON</th>
                                        <th> İŞLEMLER</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Donation)
                                    {
                                        <tr>
                                            <td>@item.Yardim_Tur</td>
                                            <td>@item.Yardim_Urun</td>
                                            <td>@item.Yardim_Miktar</td>
                                            <td>@item.Yardim_Aciklama</td>
                                            <td>@item.Yardim_Tarih</td>
                                            <td>@item.Yardim_Ysvr_Adisoyadi</td>
                                            <td>@item.Yardim_Ysvr_Telno</td>
                                            <td>
                                                <a class="btn btn-danger btn-sm" asp-controller="Donation" asp-action="Edit" asp-route-id="@item.Yardim_Id">
                                                    DÜZENLE
                                                </a>
                                                <a class="btn btn-danger btn-sm" asp-controller="Donation" asp-action="Delete" asp-route-id="@item.Yardim_Id">
                                                    SİL
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

@section scripts{
    <script type="text/javascript" class="init">

        $(document).ready(function () {
            $('#datatables').DataTable();
        });

    </script>
    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });
    </script>
}