Yoceyder.WebUI/Controllers/ChildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yoceyder.WebUI.Entity;
using Yoceyder.WebUI.Models.ViewModels;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class ChildController : Controller
    {
        private IUnitOfWork uow;

        public ChildController(IUnitOfWork _uow)
        {
            uow = _uow;
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.idal = (id);
            return View();
        }
        [HttpPost]
        public IActionResult Create(int id, Child entity)
        {
            if (ModelState.IsValid)
            {
                uow.Children.SaveChild(entity);
                TempData["message"] = $"{entity.Cocuk_AdiSoyadi} yardım başarılı bir şekilde eklendi.";
                return Redirect("~/Parents/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(uow.Children.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id ,Child entity)
        {
            if (ModelState.IsValid)
            {
                uow.Children.UpdateChild(entity);
                TempData["message"] = $"{entity.Cocuk_AdiSoyadi} kayıt başarılı bir şekilde güncellendi.";
                return Redirect("~/Child/Profile/" + id);
            }
            return View(entity);
        }

        [HttpGet]
        public IActionResult Profile(int id)
        {
            Child childs = new Child();
            childs = uow.Children.GetById(id);
            var sch = uow.Scholarships.GetAll().Where(k => k.Burs_Cocuk_Id == id);
            CSViewModel cs = new CSViewModel();
            cs.Child = childs;
            cs.Scholarship = sch;
            return View(cs);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(uow.Children.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id,int id2)
        {
            uow.Children.DeleteChild(id);
            TempData["message"] = $"{id} numaralı kayıt silindi.";

            return Redirect("~/Parents/Profile/" + id2);
        }
    }
}

Yoceyder.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Yoceyder.WebUI.Models;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class HomeController : Controller
    {
        public class ParentsController : Controller
        {
            private IUnitOfWork uow;

            public ParentsController(IUnitOfWork _uow)
            {
                uow = _uow;
            }

            public IActionResult Index(int id)
            {
                var index = uow.Parents.GetById(id);
                return View("Index", index);
            }
        }
    }
}

Yoceyder.WebUI/Controllers/ScholarshipController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Yoceyder.WebUI.Entity;
using Yoceyder.WebUI.Repository.Abstrack;

namespace Yoceyder.WebUI.Controllers
{
    public class ScholarshipController : Controller
    {
        private IUnitOfWork uow;

        public ScholarshipController(IUnitOfWork _uow)
        {
            uow = _uow;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create(int id)
        {
            ViewBag.idal = (id);
            return View();
        }
        [HttpPost]
        public IActionResult Create(int id, Scholarship entity)
        {
            if (ModelState.IsValid)
            {
                uow.Scholarships.SaveScholarship(entity);
                TempData["message"] = $"{entity.Burs_Id} burs başarılı bir şekilde eklendi.";
                return Redirect("~/Child/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(uow.Scholarships.GetById(id));
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirm(int id, int id2)
        {
            uow.Scholarships.DeleteScholarship(id);
            TempData["message"] = $"{id} numaralı kayıt silindi.";
            return Redirect("~/Child/Profile/" + id2);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(uow.Scholarships.GetById(id));
        }
        [HttpPost]
        public IActionResult Edit(int id, Scholarship entity)
        {
            if (ModelState.IsValid)
            {
                uow.Scholarships.UpdateScholarship(entity);
                TempData["message"] = $"{entity.Burs_Miktar} tl miktarındaki burs başarılı bir şekilde güncellendi.";
                return Redirect("~/Child/Profile/" + id);
            }
            else
            {
                return View(entity);
            }
        }
    }
}

Yoceyder.WebUI/Views/Child/Create.cshtml
@model Child
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <h1>YARDIM OLUŞTUR</h1>
    <br />
    <form asp-controller="Child" asp-action="Create" method="post" enctype="multipart/form-data">
        <input type="hidden" value="@ViewBag.idal" asp-for="Vasi_Id" />
        <div class="form-group">
            <div class="form-group">
                <label asp-for="Cocuk_Tc"> TC KİMLİK NUMARASI </label>
                <input type="text" asp-for="Cocuk_Tc" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Cocuk_AdiSoyadi"> ADI SOYADI </label>
                <input type="text" asp-for="Cocuk_AdiSoyadi" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Cocuk_Cinsiyet"> CİNSİYET </label>
                <input type="text" asp-for="Cocuk_Cinsiyet" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Cocuk_DogumTarihi"> DOĞUM TARİHİ </label>
                <input  asp-for="Cocuk_DogumTarihi" class="form-control">
            </div>
            <div class="form-group">
                <label asp-for="Cocuk_OgrenimDurumu"> ÖĞRENİM DURUMU </label>
                <input type="text" asp-for="Cocuk_OgrenimDurumu" class="form-control">
            </div>
            <div class="bg-light">
                <div class="form-group">
                    <label asp-for="Cocuk_OkulAdi"> OKUL ADI </label>
                    <textarea asp-for="Cocuk_OkulAdi" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_Sinif"> SINIF </label>
                    <input type="text" asp-for="Cocuk_Sinif" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_VasiYakinlik"> VASİ YAKINLIK </label>
                    <input type="text" asp-for="Cocuk_VasiYakinlik" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_KaldigiYer"> KALDIĞI YER </label>
                    <input type="text" asp-for="Cocuk_KaldigiYer" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_AnneAdi"> ANNE ADI </label>
                    <input type="text" asp-for="Cocuk_AnneAdi" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_BabaAdi"> BABA ADI </label>
                    <input type="text" asp-for="Cocuk_BabaAdi" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_AnneDurum"> ANNE DURUM </label>
                    <input type="text" asp-for="Cocuk_AnneDurum" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_BabaDurum"> BABA DURUM </label>
                    <input type="text" asp-for="Cocuk_BabaDurum" class="form-control">
                </div>
            </div>
            <button type="submit" class="btn btn-primary"> EKLE </button>
            <a class="btn btn-danger" asp-controller="Parents" asp-action="Profile" asp-route-id="@ViewBag.idal">
                İPTAL
            </a>
        </div>
    </form>
</div>

Yoceyder.WebUI/Views/Child/Delete.cshtml
@model Child
@{
    ViewData["Title"] = "Delete";
}

    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2>
                    <b> @Model.Cocuk_AdiSoyadi</b> isimli çocuğu silmek istiyormusunuz ?
                </h2>

                <form asp-controller="Child" asp-action="Delete" asp-route-id="@Model.Cocuk_Id" asp-route-id2="@Model.Vasi_Id" method="post">
                    <input type="hidden" asp-for="Cocuk_Id" />
                    <button type="submit" class="btn btn-primary">SİL</button>
                    <a class="btn btn-danger" asp-controller="Child" asp-action="profile" asp-route-id="@Model.Cocuk_Id">
                        İPTAL
                    </a>
                </form>
            </div>
        </div>
    </div>

Yoceyder.WebUI/Views/Child/Edit.cshtml
@model Child
@{
    ViewData["Title"] = "Edit";
}

    <div class="container">
        <h1>YARDIM OLUŞTUR</h1>
        <br />
        <form asp-controller="Child" asp-action="Edit" asp-route-id="@Model.Cocuk_Id" method="post" enctype="multipart/form-data">
            <input type="hidden"  asp-for="Cocuk_Id" />
            <div class="form-group">
                <div class="form-group">
                    <label asp-for="Cocuk_Tc"> TC KİMLİK NUMARASI </label>
                    <input type="text" asp-for="Cocuk_Tc" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_AdiSoyadi"> ADI SOYADI </label>
                    <input type="text" asp-for="Cocuk_AdiSoyadi" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_Cinsiyet"> CİNSİYET </label>
                    <input type="text" asp-for="Cocuk_Cinsiyet" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_DogumTarihi"> DOĞUM TARİHİ </label>
                    <input asp-for="Cocuk_DogumTarihi" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Cocuk_OgrenimDurumu"> ÖĞRENİM DURUMU </label>
                    <input type="text" asp-for="Cocuk_OgrenimDurumu" class="form-control">
                </div>
                <div class="bg-light">
                    <div class="form-group">
                        <label asp-for="Cocuk_OkulAdi"> OKUL ADI </label>
                        <textarea asp-for="Cocuk_OkulAdi" class="form-control"></textarea>
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_Sinif"> SINIF </label>
                        <input type="text" asp-for="Cocuk_Sinif" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_VasiYakinlik"> VASİ YAKINLIK </label>
                        <input type="text" asp-for="Cocuk_VasiYakinlik" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_KaldigiYer"> KALDIĞI YER </label>
                        <input type="text" asp-for="Cocuk_KaldigiYer" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_AnneAdi"> ANNE ADI </label>
                        <input type="text" asp-for="Cocuk_AnneAdi" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_BabaAdi"> BABA ADI </label>
                        <input type="text" asp-for="Cocuk_BabaAdi" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_AnneDurum"> ANNE DURUM </label>
                        <input type="text" asp-for="Cocuk_AnneDurum" class="form-control">
                    </div>
                    <div class="form-group">
                        <label asp-for="Cocuk_BabaDurum"> BABA DURUM </label>
                        <input type="text" asp-for="Cocuk_BabaDurum" class="form-control">
                    </div>
                </div>
                <button type="submit" class="btn btn-primary"> KAYDET </button>
                <a class="btn btn-danger" asp-controller="Child" asp-action="Profile" asp-route-id="@Model.Cocuk_Id">
                    İPTAL
                </a>
            </div>
        </form>
    </div>

Yoceyder.WebUI/Views/Child/Profile.cshtml
@model CSViewModel
@{
    ViewData["Title"] = "Profile";
}

    <div class="card text-center">
        <div class="card-header">
            ÇOCUK PROFİL BİLGİLERİ
        </div>
        <div class="card-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-2">

                    </div>
                    <div class="col-md-2">
                        <table class="table table-borderless">
                            <thead>

                            </thead>
                            <tbody>
                                <tr>
                                    <td><h6 class="text-dark"> <u> TC KİMLİK </u>  </h6> <h6> @Model.Child.Cocuk_Tc  </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> İSİM SOYİSİM  </u>  </h6> <h6> @Model.Child.Cocuk_AdiSoyadi  </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> CİNSİYET  </u>  </h6> <h6> @Model.Child.Cocuk_Cinsiyet  </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> DOĞUM TARİHİ </u>  </h6> <h6> @Model.Child.Cocuk_DogumTarihi </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> ÖĞRENİM DURUMU </u>  </h6> <h6> @Model.Child.Cocuk_OgrenimDurumu </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> OKUL / SINIF </u>  </h6> <h6> @Model.Child.Cocuk_OkulAdi / @Model.Child.Cocuk_Sinif </h6></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-2">
                        <table class="table table-borderless">
                            <thead>

                            </thead>
                            <tbody>
                                <tr>
                                    <td><h6 class="text-dark"> <u> VASİ YAKINLIK DERECESİ  </u>  </h6> <h6> @Model.Child.Cocuk_VasiYakinlik</h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> ÇOCUĞUN KALDIĞI YER  </u>  </h6> <h6> @Model.Child.Cocuk_KaldigiYer</h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> ANNE ADI </u>  </h6> <h6> @Model.Child.Cocuk_AnneAdi </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> BABA ADI </u>  </h6> <h6> @Model.Child.Cocuk_BabaAdi </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> ANNE DURUM   </u>  </h6> <h6> @Model.Child.Cocuk_AnneDurum  </h6></td>
                                </tr>
                                <tr>
                                    <td><h6 class="text-dark"> <u> BABA DURUM   </u>  </h6> <h6> @Model.Child.Cocuk_BabaDurum </h6></td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <div class="card" style="width: 18rem;">
                            <img src="~/images/imagess.png" class="card-img-top" alt="...">
                            <br />
                            <a class="btn btn-primary btn-sm" asp-controller="Child" asp-action="Edit" asp-route-id="@Model.Child.Cocuk_Id">
                                DÜZENLE
                            </a>
                            <a class="btn btn-danger btn-sm" asp-controller="Child" asp-action="Delete" asp-route-id="@Model.Child.Cocuk_Id">
                                PROFİLİ SİL
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
    <div class="card text-center">
        <div class="card-header">
            <h3>  BURSLAR </h3>

            <a class="btn btn-danger btn-sm" asp-controller="Scholarship" asp-action="Create" asp-route-id="@Model.Child.Cocuk_Id">
                BURS EKLE
            </a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <br />
                    <br />
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">MİKTAR</th>
                                <th scope="col"> SÜRE </th>
                                <th scope="col"> İBAN </th>
                                <th scope="col">İBAN SAHİBİ </th>
                                <th scope="col">BANKA ADI</th>
                                <th scope="col">B: ADI SOYADI</th>
                                <th scope="col">B: TELEFON</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Scholarship)
                            {
                            <tr>
                                <td>@item.Burs_Miktar</td>
                                <td>@item.Burs_Sure</td>
                                <td>@item.Burs_Iban</td>
                                <td>@item.Burs_IbanSahibi</td>
                                <td>@item.Burs_BankaAdi</td>
                                <td>@item.Burs_BsvrAdiSoyadi</td>
                                <td>@item.Burs_BsvrTelefon</td>

                                <td>
                                    <a class="btn btn-danger btn-sm" asp-controller="Scholarship" asp-action="Edit" asp-route-id="@item.Burs_Id">
                                        DÜZENLE
                                    </a>
                                    <a class="btn btn-danger btn-sm" asp-controller="Scholarship" asp-action="Delete" asp-route-id="@item.Burs_Id">
                                        SİL
                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>